create table if not exists customers(
		customer_id	int	primary key,
		age	int,
		gender	varchar(20),	
		item_purchased	varchar(50),	
		category	varchar(50)	,
		purchase_amount	int	,
		location	varchar(50),	
		size	varchar(50)	,
		color	varchar(50)	,
		season	varchar(50)	,
		review_rating DECIMAL(10, 2),	
		subscription_status	varchar(50),	
		shipping_type	varchar(50),	
		discount_applied	varchar(50),	
		previous_purchases	varchar(50)	,
		payment_method	varchar(50)	,
		frequency_of_purchases	varchar(50),	
		frequency_of_purchases_days	int	,
		age_Group	varchar(50)

);

ALTER TABLE customers
ALTER COLUMN previous_purchases TYPE INT
USING previous_purchases::INT;

select * from customers;
COPY customers FROM 'C:\Users\Samad\Downloads\customer_shopping_behavior_cleaned - Copy.csv' 
DELIMITER ',' 
CSV HEADER;

select * from customers;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue from customers
group by(gender);

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id ,
       purchase_amount
from customers
where purchase_amount> (select avg(purchase_amount) from customers) and discount_applied='Yes';

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,avg(purchase_amount) as Avg_Purchase from customers
where shipping_type='Express' or shipping_type='Standard'
group by(shipping_type);

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,sum(purchase_amount) as total_revenue, avg(purchase_amount) as avg_purchased from customers
group by(subscription_status);

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
       (SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) * 100) / COUNT(*) AS p
FROM customers
GROUP BY item_purchased
ORDER BY p desc
limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT previous_purchases,
       CASE
           WHEN previous_purchases = 1 THEN 'New'
           WHEN previous_purchases >= 2 AND previous_purchases <= 10 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customers;
--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repprevious purchases from customerseat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue from customers
group by age_group
ORDER BY revenue desc;
